server:
  port: 8082
spring:
  application:
    name: api-gateway
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/api-gateway
    username: emmantoksjr
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    gateway:
      routes:
        - id: BILL-PAYMENT
          uri: lb://BILL-PAYMENT-SERVICE
          predicates:
            - Path=/bill-payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: BILL-PAYMENT-SERVICE
                fallbackuri: forward:/BillPaymentServiceFallBack
jwt:
  secret: curvwind